### ISSUE TITLE
Windows install breaking, cannot npm install after bundle

### ISSUE THREAD

**Issue by Jim-Salmons** [zooniverse/scribeAPI#272]
Following the Windows installation instructions, everything seems to go A-OK until Step 10 where 'npm install' after the bundle gets a ''Couldn't read dependencies" error with "Error: 'version' field missing.

The only other anomaly I had before this show-stopper was in Step 9. After cloning the repo from GitHub and changing directory to the newly cloned scribeAPI directory, I got:

	ruby-2.0.0-p647 is not installed.
	To install do: 'rvm install ruby-2.0.0-p647'

I ignored this message and did the 'bundle' which appears to have worked okay. At this point, the 'npm install' following the bundle fails with the 'version field missing'

**Comment by beefoo** [comment]
Hmm. Maybe try to edit the [.ruby-version](https://github.com/zooniverse/scribeAPI/blob/master/.ruby-version) file to read `2.1.5` (instead of 2.0.0)?  I'm not sure why that file's there in the first place, but I think that may be the issue

**Comment by Jim-Salmons** [comment]
Thanks for the quick reply... Am a noob at Ruby but have a buddy to lean on as needed. Spent decades as a hardcore Smalltalker. Also new to Vagrant, so pardon the extra lameness getting going.

I tweaked the file as you mentioned to '2.1.5' which didn't fix the issue, but looking at the log/error, I see:

	System Linux 3.2.0-23-generic-pae
	command "node" "/usr/bin/npm" "install"
	cwd /vagrant/scribeAPI
	node -v v0.6.12
	npm -v 1.1.4
	message 'version' field missing
	message 'version' Must be X.Y.Z, with an optional trailing tag.
	message See the section on 'version' in `npm help json`

which seems to be implicating the 'node' package!? Will investigate this, but this is looking like a "somebody else's gotcha"

**Comment by Jim-Salmons** [comment]
A-ha! I have made some progress... the error is about not 'version' for the 'scribeAPI' itself, not any of its dependency listings. When I put in a placeholder version of '0.0.1', I got a new error about incompatible versions of dependencies! As per here (will work along these lines after afternoon exercise):

    vagrant@precise32:/vagrant/scribeAPI$ npm install
	npm http GET http://registry.npmjs.org/browserify-incremental
	npm http GET http://registry.npmjs.org/coffee-reactify
	npm http GET http://registry.npmjs.org/coffee-script
	npm http GET http://registry.npmjs.org/json-api-client
	npm http GET http://registry.npmjs.org/normalize-styl
	npm http GET http://registry.npmjs.org/normalize.css
	npm http GET http://registry.npmjs.org/react
	npm http GET http://registry.npmjs.org/react-router
	npm http GET http://registry.npmjs.org/coffee-react-transform
	npm http GET http://registry.npmjs.org/jest-cli
	npm http GET http://registry.npmjs.org/browserify
	npm http 200 http://registry.npmjs.org/coffee-script
	npm http 200 http://registry.npmjs.org/coffee-reactify

	npm ERR! Error: No compatible version found: coffee-script@'^1.9.3'
	npm ERR! Valid install targets:
	npm ERR! ["0.7.0","0.7.1","0.7.2","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4","0.9.5
	","0.9.6","1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.3.0","1.3.1
	","1.3.2","1.3.3","1.4.0","1.5.0","1.6.0","1.6.1"]
	npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
	npm ERR!     at /usr/share/npm/lib/cache.js:375:15
	npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7
	)
	npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
	npm ERR! You may report this log at:
	npm ERR!     <http://bugs.debian.org/npm>
	npm ERR! or use
	npm ERR!     reportbug --attach /vagrant/scribeAPI/npm-debug.log npm
	npm ERR!
	npm ERR! System Linux 3.2.0-23-generic-pae
	npm ERR! command "node" "/usr/bin/npm" "install"
	npm ERR! cwd /vagrant/scribeAPI
	npm ERR! node -v v0.6.12
	npm ERR! npm -v 1.1.4
	npm ERR! message No compatible version found: coffee-script@'^1.9.3'
	npm ERR! message Valid install targets:
	npm ERR! message ["0.7.0","0.7.1","0.7.2","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4
	","0.9.5","0.9.6","1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.3.0
	","1.3.1","1.3.2","1.3.3","1.4.0","1.5.0","1.6.0","1.6.1"]
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     /vagrant/scribeAPI/npm-debug.log
	npm not ok

**Comment by chrissnyder** [comment]
I'm going to guess it's the Node version it's trying to use from `package.json` that's messing it up. What happens if you remove the `engines` declaration from `package.json`?

**Comment by Jim-Salmons** [comment]
Darn, this is incredibly frustrating but making progress... 2 steps forward, 1 back...

After beating my head on this for the evening, I eventually found the big 'Gotcha!' in the current instructions for Windows installation as per here: https://goo.gl/bMV8zd.

_Step 8_ currently reads:

	sudo apt-get install nodejs
	sudo apt-get install npm
	npm config set registry http://registry.npmjs.org/

however, this installs moldy old nodejs and npm (nodejs is 0.6.12 and npm is version 1.1.4!) via Ubuntu's repo which will never work.

_Step 8 that worked for me_ is as per the recommendation for Ubuntu installation of a binary distrubtion here (https://goo.gl/NygOZv):

	curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
	sudo apt-get install -y nodejs

The subsequent "npm install" then works (which it will not do with the default Ubuntu. (Note, too, that npm is now included in nodejs, so no need to load it specifically.) This results in nodejs version 0.12.7 and npm version 2.11.3 being installed which is leap-years ahead of the Ubuntu distro grabbed by the current instructions.

At this point, everything was going so positively that I expected the rake to breeze through but no such luck... here is the top entries from the error retort (called with --trace):

	vagrant@precise32:/vagrant/scribeAPI$ rake db:create db:migrate db:seed --trace
	** Invoke db:create (first_time)
	** Invoke environment (first_time)
	** Execute environment
	Init: OAUTH providers: []
	rake aborted!
	BrowserifyRails::BrowserifyError: Unable to run node_modules/.bin/browserify. En
	sure you have installed it with npm.
	  (in /vagrant/scribeAPI/app/assets/javascripts/components.js.coffee)
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/browserify-rails-0.9.3/lib/browserify-ra
	ils/browserify_processor.rb:56:in `ensure_commands_exist!'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/browserify-rails-0.9.3/lib/browserify-ra
	ils/browserify_processor.rb:10:in `prepare'
	/home/vagrant/.rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt/template.rb:79:in `i
	nitialize'

Although the complaint seems to be that browserify is not installed, it is in fact loaded and available... so I am thinking this may be a false lead.

Any ideas what is akimbo!? I'm thinking maybe there are no OAUTH providers configured? Will investigate and ready for any suggestions... so close... so close... :-)

-: Jim :-

**Comment by robertloeberdevelopment** [comment]
Thanks a lot Jim! 
I had the same issue (aug 2018) , also with Scribe on vagrant in Windows. Now it appears that Node version 0.12 is deprecated. I solved it with:

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

Robert
