### ISSUE TITLE
Routing error in local project after sync with upstream repo

### ISSUE THREAD

**Issue by tufixm** [zooniverse/scribeAPI#531]
Most likely not a bug, just a question, since I am sure I am missing something locally.

I synced my local repo to the scribeAPI repo on git just this morning, then I ran `bundle install`

I can load the project with the rake command, then the server starts without any problem, but as soon as I go to localhost:3000 and click on the Mark workflow, I get the following in the server console and no task displayed (screen shows only the background image):

Started GET "/project/style.css" for 127.0.0.1 at 2015-11-05 11:59:00 +0100

ActionController::RoutingError (No route matches [GET] "/project/style.css"):
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in 'call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in 'block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in 'block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in 'tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in 'tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in 'call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in 'call_with_quiet_assets'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  request_store (1.2.0) lib/request_store/middleware.rb:8:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  rack (1.5.5) lib/rack/runtime.rb:17:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  rack (1.5.5) lib/rack/lock.rb:17:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  railties (4.0.13) lib/rails/engine.rb:511:in 'call'
  railties (4.0.13) lib/rails/application.rb:97:in 'call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in 'call'
  rack (1.5.5) lib/rack/content_length.rb:14:in 'call'
  puma (2.14.0) lib/puma/server.rb:541:in 'handle_request'
  puma (2.14.0) lib/puma/server.rb:388:in 'process_client'
  puma (2.14.0) lib/puma/server.rb:270:in 'block in run'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in 'call'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in 'block in spawn_thread'

  Rendered /Users/tufixm/.rvm/gems/ruby-2.1.5@scribe/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_trace.erb (3.7ms)
  Rendered /Users/tufixm/.rvm/gems/ruby-2.1.5@scribe/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/routes/_route.html.erb (19.5ms)
  Rendered /Users/tufixm/.rvm/gems/ruby-2.1.5@scribe/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/routes/_table.html.erb (45.2ms)
  Rendered /Users/tufixm/.rvm/gems/ruby-2.1.5@scribe/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (302.1ms)

**Comment by tufixm** [comment]
Like I said, not a bug. Most likely a local gem issue which got solved after I ran the bundler again.
I will close it.
