### ISSUE TITLE
[ProjectSetup] npm install fails

### ISSUE THREAD

**Issue by tufixm** [zooniverse/scribeAPI#564]
Hello,
I'm trying to setup a scribeAPI environment on a Debian system, following your Unix Setup page.
I'm failing at the last step, when doing `npm install`. Any of you are familiar with it or have any idea about a fix? Thank you.
```
npm install
npm WARN package.json scribeAPI@ No repository field.
npm WARN engine jest-cli@0.4.19: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.4","npm":"1.4.21"})
 
> contextify@0.1.15 install /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.0-1-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/cssstyle/lib/properties/webkitBoxDirection.js'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/cssstyle/lib/properties/webkitBoxDirection.js
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /home/tufixm/.npm/sntp/1.0.9/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/hoek/2.16.3/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/boom'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  jsdom@0.10.6 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/boom']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/boom' }
npm ERR! tar.unpack untar error /home/tufixm/.npm/inherits/2.0.1/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/sshpk/1.7.3/package.tgz
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/json-schema-draft4/allOf.json'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/json-schema-draft4/allOf.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /home/tufixm/.npm/verror/1.3.6/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/json-schema/0.2.2/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/handlebars/4.0.5/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/argparse/1.0.4/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/esprima/2.7.1/package.tgz
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/escodegen/node_modules/source-map/build/prefix-source-map.jsm'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/escodegen/node_modules/source-map/build/prefix-source-map.jsm
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /home/tufixm/.npm/resolve/1.1.6/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/has-ansi/2.0.0/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/escape-string-regexp/1.0.4/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/ansi-styles/2.1.0/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/supports-color/2.0.0/package.tgz
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/commander/node_modules/graceful-readlink/LICENSE'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/commander/node_modules/graceful-readlink/LICENSE
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /home/tufixm/.npm/strip-ansi/3.0.0/package.tgz
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/readme.md'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/readme.md
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /home/tufixm/.npm/balanced-match/0.3.0/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/concat-map/0.0.1/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/wrappy/1.0.1/package.tgz
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tufixm/projects/scribeAPI/npm-debug.log
npm ERR! not ok code 0
tufixm@barney:~/projects/scribeAPI$ npm config set registry http://registry.npmjs.org/
tufixm@barney:~/projects/scribeAPI$ npm install
npm WARN package.json scribeAPI@ No repository field.
npm WARN package.json json-api-client@0.2.11 No repository field.
npm WARN engine jest-cli@0.4.19: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.4","npm":"1.4.21"})
 
> contextify@0.1.15 install /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.0-1-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/cssstyle/lib/properties'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  jsdom@0.10.6 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/cssstyle/lib/properties']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/cssstyle/lib/properties' }
npm ERR! tar.unpack untar error /home/tufixm/.npm/boom/2.10.1/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/is-my-json-valid/2.12.4/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/hoek/2.16.3/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/extsprintf/1.0.2/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/process-nextick-args/1.0.6/package.tgz
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/cssstyle/lib/properties/src.js'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/cssstyle/lib/properties/src.js
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/sntp/examples'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  hawk@3.1.3 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/sntp/examples']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/hawk/node_modules/sntp/examples' }
npm ERR! tar.unpack untar error /home/tufixm/.npm/sntp/1.0.9/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  jest-cli@0.4.19 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples' }
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! tar.unpack untar error /home/tufixm/.npm/handlebars/4.0.5/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  readable-stream@2.0.5 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is' }
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  jsprim@1.2.2 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror' }
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  har-validator@2.0.6 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi' }
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/index.js'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/index.js
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/index.js'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/has-ansi/index.js
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /home/tufixm/.npm/strip-ansi/3.0.0/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/sshpk/1.7.3/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/graceful-readlink/1.0.1/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/json-schema/0.2.2/package.tgz
npm ERR! tar.unpack untar error /home/tufixm/.npm/escape-string-regexp/1.0.4/package.tgz
npm WARN optional dep failed, continuing source-map@0.2.0
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/ansi-styles/readme.md'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/ansi-styles/readme.md
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! Error: ENOENT: no such file or directory, open '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color/readme.md'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.3.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/tufixm/projects/scribeAPI
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.21
npm ERR! path /home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/supports-color/readme.md
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror/examples'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  request@2.67.0 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror/examples']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror/examples' }
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror/examples'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  http-signature@1.1.0 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror/examples']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/jsdom/node_modules/request/node_modules/http-signature/node_modules/jsprim/node_modules/verror/examples' }
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  js-yaml@3.5.2 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/js-yaml/node_modules/argparse/examples' }
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/resolve/test/resolver'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  istanbul@0.3.22 { [Error: ENOTEMPTY: directory not empty, rmdir '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/resolve/test/resolver']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/tufixm/projects/scribeAPI/node_modules/jest-cli/node_modules/istanbul/node_modules/resolve/test/resolver' }
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tufixm/projects/scribeAPI/npm-debug.log
npm ERR! not ok code 0
```

**Comment by tufixm** [comment]
In case anyone has this issue as well, here's what worked for me:
https://github.com/npm/npm/issues/11335#issuecomment-176628662
