### ISSUE TITLE
uninitialized constant ActiveModel::SerializerSupport

### ISSUE THREAD

**Issue by benjaminh** [zooniverse/scribeAPI#588]
When I try to start the server `rails s`, I get the following error :
```
/home/user/.rvm/gems/ruby-2.1.5@scribe/gems/mongoid-serializer-0.0.5/lib/mongoid/serializer.rb:6:in `configure!': uninitialized constant ActiveModel::SerializerSupport (NameError)
	from /home/user/.rvm/gems/ruby-2.1.5@scribe/gems/mongoid-serializer-0.0.5/lib/mongoid/serializer.rb:31:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:85:in `require'
	from /home/user/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:85:in `rescue in block in require'
	from /home/user/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:68:in `block in require'
	from /home/user/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
	from /home/user/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
	from /home/user/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
	from /home/user/Documents/MSH/RECITAL/scribeAPI/config/application.rb:12:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.1.5@scribe/gems/railties-4.0.13/lib/rails/commands.rb:74:in `require'
	from /home/user/.rvm/gems/ruby-2.1.5@scribe/gems/railties-4.0.13/lib/rails/commands.rb:74:in `block in <top (required)>'
	from /home/user/.rvm/gems/ruby-2.1.5@scribe/gems/railties-4.0.13/lib/rails/commands.rb:71:in `tap'
	from /home/user/.rvm/gems/ruby-2.1.5@scribe/gems/railties-4.0.13/lib/rails/commands.rb:71:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
`mongoid-serializer` is installed, and I did not get errors during previous setup steps (except those indicated in #587 that I managed to get rid of on an Ubuntu 14.04 64 bits distro)

**Comment by qjhart** [comment]
FWIW I had a similar issue on an installation.  I downgraded model_active_serializers (originally 0.10.0), and that seemed to fix the problem 

```
$ grep serializer Gemfile
gem 'active_model_serializers', '~>0.9.4'
gem 'mongoid-serializer', '~>0.0.5'
```

**Comment by benjaminh** [comment]
That did fix the problem. Thank you !

**Comment by ztsuperman** [comment]
@qjhart Thanks bro! You saved my website.
