### ISSUE TITLE
NPM not ok in Windows Setup

### ISSUE THREAD

**Issue by vlarmour** [zooniverse/scribeAPI#597]
I am trying to set up Scribe on my Windows machine and when I get to step 10 - Set up gems and modules I get multiple errors with the npm install:
vagrant@precise32:/vagrant/scribeAPI$ npm install
npm http GET http://registry.npmjs.org/browserify
npm http GET http://registry.npmjs.org/browserify-incremental
npm http GET http://registry.npmjs.org/coffee-reactify
npm http GET http://registry.npmjs.org/coffee-script
npm http GET http://registry.npmjs.org/json-api-client
npm http GET http://registry.npmjs.org/normalize-styl
npm http GET http://registry.npmjs.org/normalize.css
npm http GET http://registry.npmjs.org/react
npm http GET http://registry.npmjs.org/react-router
npm http GET http://registry.npmjs.org/coffee-react-transform
npm http GET http://registry.npmjs.org/jest-cli
npm http 200 http://registry.npmjs.org/browserify-incremental

npm ERR! Error: No compatible version found: browserify-incremental@'^3.0.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.1.1","0.1.2","0.1.3","1.0.0","1.3.0","1.4.0","1.5.0","2.0.0","3.0.0","3.0.1","3.1.0","3.1.1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at /usr/share/npm/lib/cache.js:375:15
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /vagrant/scribeAPI/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /vagrant/scribeAPI
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: browserify-incremental@'^3.0.1'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.1","0.1.0","0.1.1","0.1.2","0.1.3","1.0.0","1.3.0","1.4.0","1.5.0","2.0.0","3.0.0","3.0.1","3.1.0","3.1.1"]
npm http 200 http://registry.npmjs.org/coffee-reactify
npm http 200 http://registry.npmjs.org/coffee-script
npm http 200 http://registry.npmjs.org/normalize-styl
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/scribeAPI/npm-debug.log
npm not ok

I went through the package.json file and removed all the '^' dependencies and I thought all was good except I got this error: 
npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: coffeescript@1.9.3
npm ERR! Required: {"node":">=0.8.0"}
npm ERR! Actual:   {"npm":"1.1.4","node":"0.6.12"}
npm ERR!
npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /vagrant/scribeAPI
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ENOTSUP
npm ERR! message Unsupported
npm ERR! errno {}
npm http GET http://registry.npmjs.org/coffee-react
npm http GET http://registry.npmjs.org/convert-source-map
npm http GET http://registry.npmjs.org/through
npm http 200 http://registry.npmjs.org/through
npm http 200 http://registry.npmjs.org/convert-source-map
npm http 200 http://registry.npmjs.org/coffee-react
npm http GET http://registry.npmjs.org/convert-source-map/-/convert-source-map-0.3.5.tgz
npm http GET http://registry.npmjs.org/through/-/through-2.3.8.tgz
npm ERR! error installing coffee-reactify@4.0.0
npm http 200 http://registry.npmjs.org/through/-/through-2.3.8.tgz
npm http 200 http://registry.npmjs.org/convert-source-map/-/convert-source-map-0.3.5.tgz
npm http GET http://registry.npmjs.org/JSONStream
npm http GET http://registry.npmjs.org/browserify-cache-api
npm http GET http://registry.npmjs.org/through2
npm http GET http://registry.npmjs.org/xtend
npm http 200 http://registry.npmjs.org/through2
npm http 200 http://registry.npmjs.org/xtend
npm ERR! error installing browserify-incremental@3.0.1
npm http 200 http://registry.npmjs.org/JSONStream
npm http 200 http://registry.npmjs.org/browserify-cache-api
npm http GET http://registry.npmjs.org/object-assign
npm http GET http://registry.npmjs.org/qs/2.4.1
npm http 200 http://registry.npmjs.org/object-assign
npm ERR! error installing react-router@0.13.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/scribeAPI/npm-debug.log
npm not ok

Any guidance on troubleshooting or suggested fixes appreciated!

**Comment by camallen** [comment]
hi @vlarmour - what version of node are you using?

This repo is pretty old and refs >=0.10 node https://github.com/zooniverse/scribeAPI/blob/0161be525618c21637ba5206dbd9c27fe5e1ae22/package.json#L10

I tested and i got npm install working up to v6 of node, though i'm not sure if the code works (perhaps run the specs after installing and upgrading from v0.10 till you've got one that works. 

I hope this helps.
